const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const authDirectory = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(authDirectory, 'admin.html'), 'utf8');
const client = fs.readFileSync(path.join(authDirectory, 'admin-auth.js'), 'utf8');
const adminSettings = fs.readFileSync(path.join(authDirectory, 'admin.js'), 'utf8');
const settingsSource = fs.readFileSync(path.join(authDirectory, 'settings.js'), 'utf8');
const generatedVersionSource = fs.readFileSync(path.join(authDirectory, 'gas', 'version.generated.js'), 'utf8');
const server = fs.readFileSync(path.join(authDirectory, 'gas', 'Code.gs'), 'utf8');

assert.match(html, /id="adminAuthGate"/);
assert.match(html, /id="adminShell" class="admin-shell" hidden/);
assert.match(html, /admin-auth\.js/);
assert.doesNotMatch(html, /<script src="admin\.js/);
assert.match(html, /id="adminLoginId"/);
assert.match(html, /id="adminLoginPassword"/);
assert.match(html, /id="adminPasswordChangeForm"[^>]*hidden/);
assert.match(html, /초기 비밀번호 <code>a1234567890<\/code>/);
assert.doesNotMatch(html, /id="copyLatestGasCodeButton"/);
assert.match(html, /id="adminConnectionCheckButton"[^>]*>인증 서버 연결 및 버전 점검<\/button>/);
assert.match(html, /id="adminBootstrapGasUrl"/);
assert.match(html, /id="adminBootstrapGasUrlField"/);
assert.match(html, /id="adminExpectedServerVersion"/);
assert.match(html, /id="testConnectionButton"[^>]*>연결 및 버전 점검<\/button>/);
assert.match(html, /id="expectedConnectionVersion"/);
assert.match(html, /id="connectionVersionBadge"/);
assert.doesNotMatch(html, /initializeAdminAccount를 한 번 실행/);
assert.match(client, /action:\s*"admin-login-params"/);
assert.match(client, /action:\s*"admin-login"/);
assert.match(client, /action:\s*"admin-change-password"/);
assert.match(client, /action:\s*"admin-status"/);
assert.match(client, /GAS_VERSION_MISMATCH/);
assert.match(client, /await window\.FMAAuthSettingsReady/);
assert.match(client, /function readBootstrapGasUrl\(\)/);
assert.match(client, /function saveBootstrapGasUrl\(gasWebAppUrl\)/);
assert.match(client, /bootstrapGasUrlField\.hidden = Boolean\(bootstrapGasUrlInput\.value\)/);
assert.match(client, /requestUsingBootstrapUrl/);
assert.doesNotMatch(client, /defaultUrl/);
assert.doesNotMatch(client, /copyLatestGasCode/);
assert.match(client, /async function checkAdminConnection\(\)/);
assert.match(client, /Admin 시트 준비 완료/);
assert.match(client, /sessionStorage\.setItem\(sessionKey/);
assert.match(client, /script\.src = "admin\.js/);
assert.match(adminSettings, /async function testConnection\(\)/);
assert.match(adminSettings, /actualVersion !== expectedServerVersion/);
assert.match(adminSettings, /서버 버전\(\$\{actualVersion\}\)과 앱 요구 버전\(\$\{expectedServerVersion\}\)이 다릅니다/);
assert.match(adminSettings, /setConnectionVersion\(`정상 · \$\{actualVersion\}`/);
assert.match(settingsSource, /new URL\("gas\/Code\.gs", settingsScriptUrl\)/);
assert.match(settingsSource, /FMAAuthSettingsReady/);
assert.doesNotMatch(settingsSource, /serverVersion:\s*"2026-/);
assert.match(settingsSource, /generatedCodeVersion/);
assert.match(generatedVersionSource, /FMA_CODE_GS_VERSION/);
assert.match(html, /gas\/version\.generated\.js[^]*settings\.js/);
assert.match(server, /ADMIN_INITIAL_PASSWORD = 'a1234567890'/);
assert.match(server, /CODE VERSION: 2026-08-05-admin-sheet-account-v2/);
assert.match(server, /function version\(\)/);
assert.match(server, /ADMIN_SHEET_NAME = 'Admin'/);
assert.match(server, /ADMIN_SHEET_HEADERS = \['Category', 'ID', 'PW', 'etc', 'status'\]/);
assert.match(server, /writeInitialAdminRow_/);
assert.match(server, /\[ADMIN_TEMP_CATEGORY, ADMIN_ID, ADMIN_INITIAL_PASSWORD, 'init pw', ADMIN_ACTIVE_STATUS\]/);
assert.match(server, /serializeAdminProtectedPassword_/);
assert.match(server, /handleAdminChangePasswordPost_/);
assert.match(server, /ADMIN_SESSION_TTL_MS = 60 \* 60 \* 1000/);
assert.doesNotMatch(server, /getSpreadsheetOwnerEmail_/);
assert.doesNotMatch(server, /ADMIN_GRANT_PREFIX/);

console.log('admin-auth.test.cjs: 초기 비밀번호·강제 변경 관리자 인증 계약 검증 통과');
